---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: cbt-test
      path: /validate-cbt-storage-k8s-io-v1alpha1-volumesnapshotdeltatoken
  failurePolicy: Fail
  name: vvolumesnapshotdeltatoken.kb.io
  rules:
  - apiGroups:
    - cbt.storage.k8s.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - volumesnapshotdeltatokens
  sideEffects: None
