---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - volumesnapshotdeltatokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - volumesnapshotdeltatokens/finalizers
  verbs:
  - update
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - volumesnapshotdeltatokens/status
  verbs:
  - get
  - patch
  - update
