---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-snapshot-session-access-apiserver
  namespace: cbt-svc
  labels:
    api: external-snapshot-session-access
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: external-snapshot-session-access
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: external-snapshot-session-access
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: prasadg193/external-snapshot-session-access:latest
        volumeMounts:
        - mountPath: /apiserver.local.config/certificates
          name: apiserver-certs
          readOnly: true
        - mountPath: /apiserver.local.config/certificates/ca
          name: apiserver-ca-cert
          readOnly: true
        command:
        - "./apiserver"
        args:
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        env:
        - name: CBT_SERVER_CA_BUNDLE
          value: /apiserver.local.config/certificates/ca/ca.crt
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      - name: sample-driver
        image: prasadg193/sample-driver:latest
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        env:
        - name: CBT_SERVER_CERT
          value: "/apiserver.local.config/certificates/tls.crt"
        - name: CBT_SERVER_KEY
          value: "/apiserver.local.config/certificates/tls.key"
        - name: NUMBER_OF_BLOCKS
          value: "5"
      volumes:
      - name: apiserver-certs
        secret:
          secretName: external-snapshot-session-access
      - name: apiserver-ca-cert
        secret:
          secretName: external-snapshot-session-access-ca-cert
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: external-snapshot-session-access
  namespace: cbt-svc
  labels:
    api: external-snapshot-session-access
    apiserver: "true"
data:
  tls.crt: 
  tls.key: 
---
apiVersion: v1
kind: Service
metadata:
  name: external-snapshot-session-access
  namespace: cbt-svc
  labels:
    api: external-snapshot-session-access
    apiserver: "true"
spec:
  ports:
  - name: aggapi
    port: 443
    protocol: TCP
    targetPort: 443
  - name: cbt
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    api: external-snapshot-session-access
    apiserver: "true"
